### ISSUE TITLE
How can you revert to the standard cosmic theme?

### ISSUE THREAD

**Issue by muzzwood** [cosmic-utils/tweaks#26]
This is a great app, but I can't see any way to revert to the standard cosmic dark theme. Is it hidden somewhere or not yet an option?

**Comment by edfloreshz** [comment]
Tweaks doesn't have that option but if you open cosmic-settings and navigate to Desktop > Appearance and scroll down, you'll see a button to `Reset to default`

**Comment by muzzwood** [comment]
Aha perfect. Thanks a lot!
