### ISSUE TITLE
[bug] Swedish Translation Missing

### ISSUE THREAD

**Issue by bittin** [cosmic-utils/tweaks#35]
Hey!

The Swedish translation does not work as it should

**Comment by edfloreshz** [comment]
What's wrong?

**Comment by bittin** [comment]
![bild](https://github.com/user-attachments/assets/c2d152e3-d853-4809-865c-0c211e766644)

just compiled the application from source, and all text are in English, even if there is a Swedish translation file

but if i had done something bad, i am pretty busy until mid next week, but i can help out after that if needed

**Comment by edfloreshz** [comment]
Thanks, l’ll see if I can figure out what’s wrong

**Comment by bittin** [comment]
Still does not work

**Comment by edfloreshz** [comment]
Can you try setting a different language? I want to see if other available languages have the same issue, if not then there's probably something in the code causing this.

**Comment by edfloreshz** [comment]
Hope you get better soon.

**Comment by git-f0x** [comment]
I can confirm that setting the language to Serbian also doesn't change anything in the app.

**Comment by edfloreshz** [comment]
Then this is probably related to the localization code, let me check it.

**Comment by bittin** [comment]
alright thanks for the help f0x :)

**Comment by edfloreshz** [comment]
Found the issue, I'll send a fix in the next hour.

**Comment by bittin** [comment]
![bild](https://github.com/user-attachments/assets/9bfac7cc-0b86-4201-ae56-a2319bc72e84)


It is fixed now, sorry it took me a while to check, been a bit too busy
