### ISSUE TITLE
[FEATURE REQUEST] Add Reset Button for Each Page to Restore Default Values

### ISSUE THREAD

**Issue by iamkartiknayak** [cosmic-utils/tweaks#37]
**Description:**
It would be helpful to add a "Reset" button on each page to allow users to quickly revert settings back to their default values. This feature would enhance usability by offering a one-click solution for users who want to undo changes made on individual pages.

**Expected behavior:**
Save current config somewhere to refer to (custom changes made via Cosmic Settings) to reset to if we want to reset the changes that has been made in Cosmic Tweaks & not reset everything back to Cosmic DE default.

**Comment by cavaughankirov** [comment]
Agreed. Hit the MAC OS layout button, hate it, and get anything back, fans going crazy!
