### ISSUE TITLE
Request left side buttons

### ISSUE THREAD

**Issue by cavaughankirov** [cosmic-utils/tweaks#41]
Please make a tweak to move the titlebar buttons to the left side!

**Comment by iamkartiknayak** [comment]
I don't think it's possible to do that, even if it did it would break the COSMIC design.

**Comment by edfloreshz** [comment]
Yes, the COSMIC team has said that they don't intend to allow this and I can't really do much if they don't expose a way to move the window controls.

Closing for now, if in the future there's a way we can revisit this.
