### ISSUE TITLE
Tag a new release?

### ISSUE THREAD

**Issue by ryanabx** [cosmic-utils/tweaks#45]
There have been plenty of features added since the last release. Should we bump the release and publish to flathub?

CC: @edfloreshz

**Comment by edfloreshz** [comment]
Definitely!

**Comment by edfloreshz** [comment]
https://github.com/flathub/dev.edfloreshz.CosmicTweaks/pull/

**Comment by edfloreshz** [comment]
Looks like we got an error with your library @ryanabx

**Comment by edfloreshz** [comment]
I vendored all the dependencies, maybe it skipped yours?
