### ISSUE TITLE
[Feature Request] Desktop Layouts

### ISSUE THREAD

**Issue by onlyreportingissues** [cosmic-utils/tweaks#5]
Would simplify adjusting the desktop to one's liking

**Comment by edfloreshz** [comment]
This is a planned feature, thanks for opening this issue.

**Comment by ryanabx** [comment]
Glad someone has beat me to it haha

**Comment by edfloreshz** [comment]
Implemented in https://github.com/cosmic-utils/tweaks/pull/39
